[project]
name = "go2-webrtc-example"
version = "0.1.0"
description = "Unitree Go2 WebRTC Example"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-contrib-python>=4.8.0",
    "numpy",
    "aiortc",
    "pyzbar",
    "unitree-webrtc-connect @ git+https://github.com/legion1581/unitree_webrtc_connect.git",
    "unitree_sdk2py @ git+https://github.com/unitreerobotics/unitree_sdk2_python.git"
]

[tool.uv]
# uv 전용 설정 (필요시 추가)